update casefile with trello information
DIVD-NL/web-csirt pull request #432
Opened 2022-07-22 16:05 UTC by Ralphhorn

2022-08-09 14:03 UTC, MrSeccubus submitted a review, later dismissed
LGTM

2022-08-09 14:05 UTC, MrSeccubus requested changes

2022-08-09 14:05 UTC, MrSeccubus commented on _cases/DIVD-2022-00008.md
>  ---
```suggestion
---
ips: 31132
```

2022-08-09 14:06 UTC, MrSeccubus commented on _cases/DIVD-2022-00008.md
>  ---
Zodat de stats ook goed lopen.

2022-08-11 22:42 UTC, Lennaert89 submitted a review, later dismissed

2022-08-12 09:14 UTC, MrSeccubus approved these changes

2022-08-12 09:14 UTC, merged