closing divd-2021-00015
DIVD-NL/web-csirt pull request #476
Opened 2022-10-10 19:47 UTC by Ralphhorn

2022-10-10 21:09 UTC, Lennaert89 approved these changes

2022-10-11 12:59 UTC, MrSeccubus requested changes

2022-10-11 12:59 UTC, MrSeccubus commented on _cases/2021/DIVD-2021-00015.md
>  ips: 0
This is where it breaks:
```suggestion
```
This line should not be in the middle of the timeline events.

2022-10-11 12:59 UTC, MrSeccubus commented on _cases/2021/DIVD-2021-00015.md
> +  event: "Case closed no further actionable steps can be taken"
```suggestion
  event: "Case closed no further actionable steps can be taken"
ips: n/a
```
ips: 0 will give an error, because a closed case should have a number of impacted IPs

2022-10-11 12:59 UTC, MrSeccubus commented
Pipeline is running again, but the case is generating errors:
```
             Error: YAML Exception reading /root/project/_cases/2021/DIVD-2021-00015.md: (<unknown>): did not find expected key while parsing a block mapping at line 2 column 1
ERROR CasesPlugin: Case DIVD-2021-00015, does not have a author set
ERROR CasesPlugin: Case DIVD-2021-00015, does not have a lead set
ERROR CasesPlugin: Case DIVD-2021-00015 does not have an excerpt or the default excerpt
ERROR CasesPlugin: Case DIVD-2021-00015, has invalid start data '', it should be a valid date
ERROR CasesPlugin: Case DIVD-2021-00015, has invalid status '', should be 'Open' or 'Closed'
```
It looks like the

2022-10-11 21:28 UTC, MrSeccubus approved these changes

2022-10-11 21:29 UTC, merged