Update DIVD-2021-00021.md
DIVD-NL/web-csirt pull request #477
Opened 2022-10-10 19:48 UTC by Lennaert89

case closed

2022-10-10 21:07 UTC, Ralphhorn approved these changes
lgtm

2022-10-11 14:53 UTC, MrSeccubus requested changes

2022-10-11 14:53 UTC, MrSeccubus commented on _cases/2021/DIVD-2021-00021.md
> -  event: "DIVD sent out a first batch of notifications."
Missing a case closed event

2022-10-11 14:53 UTC, MrSeccubus commented on _cases/2021/DIVD-2021-00021.md
> -  event: "DIVD sent out a first batch of notifications."
Also the end date isn;t set on line 19.

2022-10-12 08:54 UTC, MrSeccubus approved these changes
Thanks for the changes.

2022-10-12 08:54 UTC, merged