Update DIVD-2021-00022.md
DIVD-NL/web-csirt pull request #478
Opened 2022-10-10 20:14 UTC by Lennaert89

closing this case

2022-10-10 21:15 UTC, Ralphhorn reviewed
lgtm

2022-10-11 14:50 UTC, MrSeccubus requested changes

2022-10-11 14:50 UTC, MrSeccubus commented on _cases/2021/DIVD-2021-00022.md
>  ips: 0
IIRC (And as case lead I should), we had quite a bit more then 0 affected IPs.

2022-10-11 14:50 UTC, MrSeccubus commented on _cases/2021/DIVD-2021-00022.md
>  ips: 0
Fixed it.

2022-10-11 14:50 UTC, MrSeccubus commented on _cases/2021/DIVD-2021-00022.md
> +For us this case has ended, anyone still vulnerable to these issues over a year after patches were made available will be notified of this together with [case 2022-00054](https://csirt.divd.nl/cases/
```suggestion
For us this case has ended, anyone still vulnerable to these issues over a year after patches were made available will be notified of this together with [case 2022-00054](/cases/DIVD-2022-00054/).
```
Relative url's please.

2022-10-11 14:53 UTC, merged