The curious case of Ms certs
DIVD-NL/web-csirt pull request #497
Opened 2022-10-16 14:44 UTC by MrSeccubus

2022-10-16 19:10 UTC, MrSeccubus commented
ERROR CasesPlugin: Case DIVD-2022-00013 does not have an excerpt or the default excerpt

2022-10-17 07:17 UTC, Lennaert89 requested changes

2022-10-17 07:17 UTC, Lennaert89 commented on _cases/2022/DIVD-2022-00013.md
> +excerpt: "Please set this to and except of a few lines.
No Excerpt?

2022-10-17 07:17 UTC, Lennaert89 commented on _cases/2022/DIVD-2022-00013.md
> +  event: "Ethics committee, ruels that case is within CoC"
typo

2022-10-23 15:44 UTC, MrSeccubus commented
See #499

2022-10-23 15:44 UTC, closed without merging