Update DIVD-2022-00019.md
DIVD-NL/web-csirt pull request #519
Opened 2022-11-07 16:24 UTC by JohnC-DIVD

Update & close case.

2022-11-07 21:51 UTC, MrSeccubus requested changes
Graag ook status op regel 6 op ‘Closed’ zetten en op regel 19 een einddatum invullen

2022-11-07 21:52 UTC, MrSeccubus submitted a review, later dismissed

2022-11-07 21:52 UTC, MrSeccubus commented on _cases/2022/DIVD-2022-00019.md
> +
```suggestion
ips: xxx
```
Graag ook nog aantal affected IP’s/applicaties invullen

2022-11-09 20:38 UTC, Lennaert89 approved these changes

2022-11-09 20:40 UTC, merged