Add casefile for Iguana CMS
DIVD-NL/web-csirt pull request #543
Opened 2023-01-03 14:32 UTC by Maximand

2023-01-03 15:27 UTC, MrSeccubus requested changes

2023-01-03 15:27 UTC, MrSeccubus commented on _cases/2022/DIVD-2022-00064.md
> +- Amr Al Hallak (reporter and finder)
```suggestion
- Amr Al Hallak (external reporter and finder)
```
Misschien even beter aangeven dat hij geen DIVD-er is, toch?

2023-01-03 15:27 UTC, MrSeccubus commented on _cases/2022/DIVD-2022-00064.md
> +
```suggestion
jekyll-secinfo:
  cve:
    url: /cves/CVE-
```
Dit zorg dat `%{ cve ... %} ` op de site blijft.

2023-01-03 15:29 UTC, Maximand commented on _cases/2022/DIVD-2022-00064.md
> +- Amr Al Hallak (reporter and finder)
Eens

2023-01-03 15:51 UTC, MrSeccubus requested changes
Voeg jij de CVEs zelf nog toe?

2023-01-03 15:51 UTC, MrSeccubus commented on _cases/2022/DIVD-2022-00064.md
> +- start: 2022-11-03
```suggestion
- start: 2022-09-08
  end: 2022-11-03
  event: Time to fix first 4 CVEs
- start: 2022-11-03
```

2023-01-03 15:51 UTC, MrSeccubus commented on _cases/2022/DIVD-2022-00064.md
> +- start: 2022-11-16
```suggestion
- start: 2022-09-08
  end: 2022-11-03
  event: Time to acknowledge first 4 CVEs
- start: 2022-11-03
```

2023-01-03 15:51 UTC, MrSeccubus commented on _cases/2022/DIVD-2022-00064.md
> +  event: "Limited disclosure."
```suggestion
  event: "Limited disclosure first four CVEs"
```

2023-01-03 15:51 UTC, MrSeccubus commented on _cases/2022/DIVD-2022-00064.md
> +jekyll-secinfo:
```suggestion
- start: 2022-11-21
  end: open
  event: Time to acknowldge additional two vulnerabilities
- start: 2022-11-21
  end: open
  event: Time to fix additional two vulnerabilities
jekyll-secinfo:
```

2023-01-04 16:14 UTC, MrSeccubus approved these changes

2023-01-04 16:14 UTC, merged