2022-00065-zyxel-multicrit
DIVD-NL/web-csirt pull request #553
Opened 2023-01-22 20:12 UTC by kormorant

Added the md file to the 2022 cases folder for DIVD-2022-00065 (zyxel multicrit)

2023-01-22 21:45 UTC, MrSeccubus requested changes
Ping me als je wilt sparren.

2023-01-22 21:45 UTC, MrSeccubus commented on _cases/2022/DIVD-2022-00065.md
> +- n/a
Weten we de CVE’s niet?

2023-01-22 21:45 UTC, MrSeccubus commented on _cases/2022/DIVD-2022-00065.md
> +#patch_status: Fully patched
```suggestion
patch_status: “Devices are end-of-life and will not be patched”
```

2023-01-22 21:45 UTC, MrSeccubus commented on _cases/2022/DIVD-2022-00065.md
> +ips: 1
Waarom 1? Case if nog open, dus ips hoeven nu nog niet gezet te worden. 
```suggestion
#ips: 1
```

2023-01-22 21:45 UTC, MrSeccubus commented on _cases/2022/DIVD-2022-00065.md
> +On February 15th 2022, [Sec Consult](https://sec-consult.com) published an advisory regarding multiple vulnerabilities on various [Zyxel](https://zyxel.com) devices.
Link naar advisory toevoegen.

2023-01-22 21:45 UTC, MrSeccubus commented on _cases/2022/DIVD-2022-00065.md
> +While some of these devices could be patched, others were EOL (end of life) and would not receive a patch. DIVD has performed scans of these devices, to notify owners/operators of the risks regarding
```suggestion
While some of these devices could be patched, others were EOL (end of life) and will not receive a patch. DIVD has performed scans for these devices, to notify owners/operators of the risks regarding the continued operation of these devices.
```

2023-01-22 21:45 UTC, MrSeccubus commented on _cases/2022/DIVD-2022-00065.md
> +If you currently own or operate any of the listed EOL devices, please consider retiring it as soon as possible. If, for whatever reason, this is not a possibility, make sure all internet facing ports
```suggestion
If you currently own or operate any of the listed EOL devices, please consider retiring/replacing it as soon as possible. If, for whatever reason, this is not a possibility, make sure all internet facing ports are closed as much as possible.
```

2023-01-22 21:45 UTC, MrSeccubus commented on _cases/2022/DIVD-2022-00065.md
> +If you came here through other means than through our direct mailing, please refer to the list published by Sec Consult and Zyxel, to determine whether your Zyel device is vulnerable and if a patch m
Link naar de lijst toevoegen.

2023-01-22 21:45 UTC, MrSeccubus commented on _cases/2022/DIVD-2022-00065.md
> +After having notified all owners/operators of relevant EOL Zyxel devices, we will intermittently scan the internet, to determine if appropriate action has been taken, and renotify if we have not rece
Je schrijft hier dat je gaat bijhouden wie er reageert en dat je mensen die gaan reageren niet meer gaat mailen. Ga je dat ook echt zo doen? Lijkt mij heel veel en behoorlijk foutgevoelig werk.

2023-01-23 07:53 UTC, kormorant commented on _cases/2022/DIVD-2022-00065.md
> +- n/a
Als ik dit document mag geloven, zijn er geen CVEs voor geregistreerd:
https://sec-consult.com/vulnerability-lab/advisory/multiple-critical-vulnerabilities-in-multiple-zyxel-devices/

2023-01-23 07:57 UTC, kormorant commented on _cases/2022/DIVD-2022-00065.md
> +ips: 1
ivm de comment eronder ging ik er vanuit dat dit een switch was die relevant was als er ips gemoeid waren met de case.

2023-01-23 08:38 UTC, MrSeccubus commented on _cases/2022/DIVD-2022-00065.md
> +- n/a
In dat geval zou ik niet voor N/a kiezen maar een een tekst die dit omschrijft.
```suggestion
- CVE-2022-4510
- The researchers described a total of 8 vulnerabilities of which 7 have not been assigned a CVE.
```

2023-01-23 08:38 UTC, MrSeccubus commented on _cases/2022/DIVD-2022-00065.md
> +ips: 1
Dit veld wordt gebruikt voor de stats achteraf. Ik zal het in de templates verduidelijken.

2023-01-23 08:55 UTC, MrSeccubus commented on _cases/2022/DIVD-2022-00065.md
> +ips: 1
Zie #554

2023-01-23 12:48 UTC, kormorant commented on _cases/2022/DIVD-2022-00065.md
> +After having notified all owners/operators of relevant EOL Zyxel devices, we will intermittently scan the internet, to determine if appropriate action has been taken, and renotify if we have not rece
Het zijn maar 500 ip adressen. Als er wat binnenkomt en ik dat van de lijst afhaal, lijkt me dat wel te doen. Bij duizenden en duizenden zal het een ander verhaal zijn, zeker.

2023-01-23 15:54 UTC, MrSeccubus commented on _cases/2022/DIVD-2022-00065.md
> +- n/a
Alleen deze nog?

2023-01-23 15:56 UTC, MrSeccubus approved these changes
Looks good to me.

2023-01-23 15:57 UTC, MrSeccubus requested changes
Mag dus niet. Ik ken mijn eigen checks niet eens

2023-01-23 15:57 UTC, MrSeccubus commented on _cases/2022/DIVD-2022-00065.md
> +- The researchers described a total of 8 vulnerabilities of which 7 have not been assigned a CVE.
```suggestion
- n/a
```

2023-01-23 15:59 UTC, MrSeccubus approved these changes
👍

2023-01-23 15:59 UTC, merged