Casefile for DIVD-2023-00006
DIVD-NL/web-csirt pull request #559
Opened 2023-02-03 14:03 UTC by JstRelax

New casefile. Please review :)

2023-02-03 15:19 UTC, MrSeccubus requested changes
Paar kleine aanpassingen

2023-02-03 15:19 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00006.md
> +title: "Unauthenticated command injection in QTS and QuTS hero "
```suggestion
title: "Unauthenticated command injection in QNAP QTS and QuTS hero "
```

2023-02-03 15:19 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00006.md
> +excerpt: ""
Graag invullen, anders staat er alleen een titel op https://csirt.divd.nl/cases/

2023-02-03 15:19 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00006.md
> +A vulnerability has been found in QNAP devices running QTS 5.0.1 and QuTS hero h5.0.1. When exploited, it is possible for attackers to inject malicious code. QNAP has linked CWE-89 to this CVE. The C
```suggestion
A vulnerability has been found in QNAP devices running QTS 5.0.1 and QuTS hero h5.0.1. When exploited, it is possible for attackers to inject malicious code. QNAP has linked {% cwe: CWE-89 %} to this CVE. The CWE is related to 'Improper Neutralization of Special Elements used in an SQL Command (or SQL injection)'. QTS 5.0.0, QTS 4.x.x, QuTS hero 5.0.0 and QuTS hero 4.5.x are not affected.
```

2023-02-03 15:19 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00006.md
> +Update your QTS or QuTS hero. This can be done by navigating to Control Panel > System > Firmware Update. Under Live Update, click Check for Update.
```suggestion
Update your QTS or QuTS hero. This can be done by navigating to Control Panel > System > Firmware Update. Under Live Update, click `Check for Update`.
```

2023-02-03 15:19 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00006.md
> +DIVD is currently working to identify vulnerable parties and notifying these. We do this by finding QNAP QTS and QNAP QuTS Hero instances and verifying their version and build number.
```suggestion
DIVD is currently working to identify vulnerable parties and notifying these. We do this by finding QNAP QTS and QNAP QuTS Hero instances and verifying their version and build number.
The notificaiton will be sent to the party responsible for the ip address accoording to the whois database. 
```

2023-02-07 10:21 UTC, JstRelax commented on _cases/2023/DIVD-2023-00006.md
> +excerpt: ""
Excerpt toegevoegd!

2023-02-07 10:41 UTC, MrSeccubus approved these changes
:+1:

2023-02-07 10:41 UTC, merged