Casefile for case 11 - FortiNAC and FortiWeb
DIVD-NL/web-csirt pull request #571
Opened 2023-02-21 17:52 UTC by Maximand

2023-02-27 08:52 UTC, MrSeccubus requested changes

2023-02-27 08:52 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00011.md
> +Upgrade your FortiNAC and/or FortiWeb instances to one of the mentioned patched versions as soon as possible.
Ik zou de versies nog even expliciet in de tekst zetten.

2023-02-28 10:37 UTC, Maximand commented on _cases/2023/DIVD-2023-00011.md
> +Upgrade your FortiNAC and/or FortiWeb instances to one of the mentioned patched versions as soon as possible.
Toegevoegd

2023-03-08 21:50 UTC, MrSeccubus approved these changes

2023-03-08 21:50 UTC, merged