Update timeline
DIVD-NL/web-csirt pull request #582
Opened 2023-03-01 20:25 UTC by sud0woodo

2023-03-07 14:44 UTC, Lennaert89 requested changes

2023-03-07 14:44 UTC, Lennaert89 commented on _cases/2023/DIVD-2023-00012.md
> +  -start: 2023-03-01
Misses a space between `-` and `start` causing the parser to complain

2023-03-08 09:29 UTC, MrSeccubus requested changes

2023-03-08 09:29 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00012.md
> +  -start: 2023-03-01
```suggestion
  - start: 2023-03-01
```

2023-03-08 09:51 UTC, Lennaert89 commented
@MrSeccubus can you review? I've committed the suggestion so can't review my own work 😅

2023-03-08 10:23 UTC, MrSeccubus approved these changes

2023-03-08 10:25 UTC, merged