Case file for DIVD-2023-00016
DIVD-NL/web-csirt pull request #594
Opened 2023-03-14 18:30 UTC by E1A

2023-03-14 20:19 UTC, martinvw commented on _cases/2023/DIVD-2023-00016.md
> +## What you can do
Misschien nog even consistent newlines boven/onder paragrafen plaatsen

2023-03-15 06:52 UTC, MrSeccubus requested changes

2023-03-15 06:52 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00016.md
> +versions: < 9.5.9 & 10.0.3
```suggestion
versions: 
- “< 9.5.9”
- “< 10.0.3”
```

2023-03-15 06:52 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00016.md
> +recommendation: "Update to the latest version or delete the vendor/htmlawed/htmlawed/htmLawedTest.php file (be careful not to touch the htmLawed.php file which is legitimate)."
Is dat laatste gee workaround?
```suggestion
recommendation: "Update to the latest version”
workaround: “Delete the vendor/htmlawed/htmlawed/htmLawedTest.php file (be careful not to touch the htmLawed.php file which is legitimate)."
```

2023-03-15 06:52 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00016.md
> +The case involves a code injection vulnerability in GLPI instances versions <=10.0.2 and <=9.5.8, caused by an old version of the htmlawed library (under /vendor/htmlawed/htmlawed/) that still contai
<10.0.3 is hetzelfde als <= 10.0.2, maar probeer het zoveel mogelijk hetzelfde te doen.

2023-03-15 11:41 UTC, MrSeccubus requested changes

2023-03-15 11:41 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00016.md
> +The case involves a code injection vulnerability in GLPI instances versions <=10.0.2 and <=9.5.8, caused by an old version of the htmlawed library (under /vendor/htmlawed/htmlawed/) that still contai
```suggestion
The case involves a code injection vulnerability in GLPI instances versions < 10.0.3 and < 9.5.9, caused by an old version of the htmlawed library (under /vendor/htmlawed/htmlawed/) that still contains the htmLawedTest.php file with code injection vulnerability.
```

2023-03-15 11:41 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00016.md
> +workaround: “Delete the vendor/htmlawed/htmlawed/htmLawedTest.php file (be careful not to touch the htmLawed.php file which is legitimate)."
```suggestion
recommendation: "Update to the latest version"
workaround: "Delete the vendor/htmlawed/htmlawed/htmLawedTest.php file (be careful not to touch the htmLawed.php file which is legitimate)."
```
Stomme smart quotes op mij telefoon.

2023-03-15 11:43 UTC, MrSeccubus approved these changes

2023-03-15 17:26 UTC, martinvw commented
@MrSeccubus kan hij ook al gemerged worden?

2023-03-15 17:50 UTC, MrSeccubus commented
Wat mij betreft wel (daarom ook de approval). 
@E1A wat jou betreft ook?

2023-03-15 18:19 UTC, E1A commented
Yes mag van mij ook

2023-03-15 21:40 UTC, merged