Update DIVD-2023-00014.md
DIVD-NL/web-csirt pull request #603
Opened 2023-04-05 17:09 UTC by kormorant

Added dates for scan start and ending, and date case was closed. Altered fixed versions layout to fall  below recommendations.

2023-04-05 17:14 UTC, Lennaert89 requested changes
Status op line 6 moet closed zijn lijkt me.
En een ingevulde end date op line 29.

2023-04-09 14:59 UTC, MrSeccubus commented
‘ips: 0‘
Moet ook toegevoegd worden.

2023-04-09 15:02 UTC, MrSeccubus commented
let op de yaml syntax van de front matter blok is niet ok. 

```
Error: YAML Exception reading /home/runner/work/web-csirt/web-csirt/_cases/2023/DIVD-2023-00014.md: (<unknown>): did not find expected key while parsing a block mapping at line 2 column 1
```

vandaar dat de build failed.

2023-04-10 10:30 UTC, kormorant commented
Build failed nu nog enkel op:
ERROR CasesPlugin: Case DIVD-2023-00014, is 'Closed' but 0 ips affected. That's not good for stats (is the ips front matter key set?)

2023-04-10 10:59 UTC, MrSeccubus requested changes

2023-04-10 10:59 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00014.md
> +ips: 0
```suggestion
ips: n/a
```

2023-04-10 11:14 UTC, MrSeccubus approved these changes

2023-04-10 11:15 UTC, merged