Casefile update 2023-00020
DIVD-NL/web-csirt pull request #614
Opened 2023-04-24 12:39 UTC by Maximand

2023-04-24 13:30 UTC, MrSeccubus commented
Build error:
```
ERROR CasesPlugin: Case DIVD-2023-00020, has an event on the timeline with invalid start ``
```

2023-04-24 13:31 UTC, MrSeccubus requested changes

2023-04-25 08:53 UTC, Maximand commented
Thanks!

2023-05-24 10:23 UTC, MrSeccubus approved these changes
:+1:

2023-05-24 10:23 UTC, merged