Create casefile DIVD-2023-00024.md
DIVD-NL/web-csirt pull request #644
Opened 2023-06-09 13:01 UTC by MrIamGr00t

Case file DIVD-2023-00024.md aangemaakt

2023-06-09 14:41 UTC, MrSeccubus requested changes

2023-06-09 14:41 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00024.md
> +- hp197
Wie is dit?

2023-06-09 14:41 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00024.md
> +GeoServer has listed 3 mitigations and a remediation step. If you can, install the provided patch immediately.
Wat zijn die 3 mitigaties?

2023-06-11 11:38 UTC, Maximand commented on _cases/2023/DIVD-2023-00024.md
> +- "< 2.22.2)"
```suggestion
- "< 2.22.2"
```

2023-06-11 12:11 UTC, MrSeccubus approved these changes
👍

2023-06-11 12:12 UTC, merged