Create DIVD-2023-00026.md
DIVD-NL/web-csirt pull request #646
Opened 2023-07-03 19:16 UTC by E1A

2023-07-03 19:40 UTC, Lennaert89 requested changes
Misschien toevoegen dat er exploit code beschikbaar is op het internet dus dat dit oplossen echt een prio is.

2023-07-03 19:40 UTC, Lennaert89 commented on _cases/2023/DIVD-2023-00026.md
> +title: "Apache Superset authentication bypass leads to RCE"
add the CVE nr in the title

2023-07-03 19:40 UTC, Lennaert89 commented on _cases/2023/DIVD-2023-00026.md
> +- Finn van der Knaap
Volgens mij hebben hier meer mensen aan gewerkt.

2023-07-03 19:40 UTC, Lennaert89 commented on _cases/2023/DIVD-2023-00026.md
> +recommendation: "Update to the latest version or rotate the SECRET_KEY"
alleen updaten is volgens mij niet genoeg om de secret key te overschrijven, change recommendation to:
Rotate the SECRET_KEY, and update to the latest version.

2023-07-03 19:40 UTC, Lennaert89 commented on _cases/2023/DIVD-2023-00026.md
> +
Add date of publishing case file to the casefile.

2023-07-03 19:40 UTC, Lennaert89 commented on _cases/2023/DIVD-2023-00026.md
> +Recently, a writeup was posted for the open source tool, Apache Superset. This is an exploration and visualization tool. The vulnerability lies with SECRET_KEY that signs the cookies of user logging
Recently, a writeup was posted for a vulnerability, tracked as CVE-2023-27524, in the open source tool Apache Superset. A default Flask SECRET_KEY is used, this key signs the cookies of user logging in. By default, this key is one of 5 standard keys, which per the software's documentation should be changed. When an attacker knows this key, they can sign their own cookies, as a result the attacker can forge their own cookies to log in as an administrator.

2023-07-03 19:40 UTC, Lennaert89 commented on _cases/2023/DIVD-2023-00026.md
> +* Consider upgrading to the latest version.
replace by:
Update to the latest version.

2023-07-03 19:40 UTC, Lennaert89 commented on _cases/2023/DIVD-2023-00026.md
> +* Rotate the SECRET_KEY by following the article on Apache on their website: https://superset.apache.org/docs/installation/configuring-superset .
Deze is belangrijker dan updaten, dus zou 'm hoger zetten.

2023-07-03 19:40 UTC, Lennaert89 commented on _cases/2023/DIVD-2023-00026.md
> +* DIVD is currently pinpointing all the vulnerable Superset servers.
pinpointing -> identifying

2023-07-03 19:40 UTC, Lennaert89 commented on _cases/2023/DIVD-2023-00026.md
> +{% include{% include timeline.html %} timeline.html %}
uh whats going on here?

2023-07-03 19:40 UTC, Lennaert89 commented on _cases/2023/DIVD-2023-00026.md
> +*[Configuring the SECRET_KEY"](https://superset.apache.org/docs/installation/configuring-superset)
space after * for valid markdown

2023-07-04 17:17 UTC, Lennaert89 requested changes

2023-07-04 17:17 UTC, Lennaert89 commented on _cases/2023/DIVD-2023-00026.md
> -{% include timeline.html %}
je hebt nu zo te zien de hele timeline er perongeluk uitgegooid, graag die er wel in

2023-07-05 07:39 UTC, Lennaert89 approved these changes

2023-07-05 07:43 UTC, Lennaert89 commented
@E1A nog steeds een build error:
> Error: YAML Exception reading /home/runner/work/web-csirt/web-csirt/_cases/2023/DIVD-2023-00026.md: (<unknown>): did not find expected key while parsing a block mapping at line 2 column 1

2023-07-05 09:04 UTC, MrSeccubus requested changes

2023-07-05 09:04 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00026.md
> +end: -
Ik denk dat dit de boosdoener van de build error is.
```suggestion
end: 
```

2023-07-05 09:07 UTC, MrSeccubus requested changes

2023-07-05 09:07 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00026.md
> +workaround: "Rotate the SECRET_KEY by following this article from Apache: [Configuring the SECRET_KEY"](https://superset.apache.org/docs/installation/configuring-superset)”
```suggestion
workaround: "Rotate the SECRET_KEY by following this article from Apache: [Configuring the SECRET_KEY](https://superset.apache.org/docs/installation/configuring-superset)”
```
Dit is de build error

2023-07-05 09:12 UTC, MrSeccubus requested changes

2023-07-05 09:12 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00026.md
> +  end: ongoing
En toen kreeg je er nog een build error bij.

```suggestion
  end: 
```
Het is even is `Start research` dus dan heb je geen end date, want de start valt op een bepaalde dag.
of:
Noem het event `research` en gebruik ipv `ongoing`, `open`

2023-07-05 09:13 UTC, MrSeccubus commented
@E1A als je docker helpt, draai dan even het `./test_it.sh` command zodat je lokaal de build errors ziet, of kijk even naar de output van de build hier op GitHub.

2023-07-05 10:46 UTC, Lennaert89 approved these changes

2023-07-05 12:07 UTC, MrSeccubus requested changes

2023-07-05 12:07 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00026.md
> +Recently, a writeup was posted for a vulnerability, tracked as CVE-2023-27524, in the open source tool Apache Superset. A default Flask SECRET_KEY is used, this key signs the cookies of user logging
```suggestion
Recently, a writeup was posted for a vulnerability, tracked as {% cve: CVE-2023-27524 %}, in the open source tool Apache Superset. A default Flask SECRET_KEY is used, this key signs the cookies of user logging in. By default, this key is one of 5 standard keys, which per the software's documentation should be changed. When an attacker knows this key, they can sign their own cookies, as a result the attacker can forge their own cookies to log in as an administrator.
```

2023-07-05 12:07 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00026.md
> +* [Configuring the SECRET_KEY"](https://superset.apache.org/docs/installation/configuring-superset)
```suggestion
* [Configuring the SECRET_KEY](https://superset.apache.org/docs/installation/configuring-superset)
```

2023-07-05 12:07 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00026.md
> +![image](https://github.com/E1A/web-csirt/assets/57531297/fb2cb5bc-9289-4a71-b67e-fa28207fef8b)
```suggestion
```
Don't think this belongs here (looks like a paste error)

2023-07-06 11:28 UTC, MrSeccubus requested changes

2023-07-06 11:28 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00026.md
> +Recently, a writeup was posted for a vulnerability, tracked as {% cve: CVE-2023-27524 %}, in the open source tool Apache Superset. A default Flask SECRET_KEY is used, this key signs the cookies of us
```suggestion
Recently, a writeup was posted for a vulnerability, tracked as {% cve CVE-2023-27524 %}, in the open source tool Apache Superset. A default Flask SECRET_KEY is used, this key signs the cookies of user logging in. By default, this key is one of 5 standard keys, which per the software's documentation should be changed. When an attacker knows this key, they can sign their own cookies, as a result the attacker can forge their own cookies to log in as an administrator.
```

2023-07-06 11:28 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00026.md
> +Recently, a writeup was posted for a vulnerability, tracked as {% cve: CVE-2023-27524 %}, in the open source tool Apache Superset. A default Flask SECRET_KEY is used, this key signs the cookies of us
My bad, ik ken mijn eigen plugin niet eens meer goed.

2023-07-06 11:30 UTC, MrSeccubus approved these changes

2023-07-06 11:31 UTC, merged