OSNexus limited disclosure and product warning
DIVD-NL/web-csirt pull request #649
Opened 2023-07-05 19:49 UTC by MrSeccubus

2023-07-05 19:50 UTC, MrSeccubus commented
Please don't merge yet.

2023-07-06 14:21 UTC, Lennaert89 requested changes

2023-07-06 14:21 UTC, Lennaert89 commented on DIVD-2021-00020.md
> +excerpt: "There are multiple discovered vulnerabilities inside OSNEXUS QuantaStor involving injection (SSRF, XSS, RCE) and privilege escalation."
Replace start by "There have been various vulnerabilities discovered inside ..."

2023-07-06 14:21 UTC, Lennaert89 commented on DIVD-2021-00020.md
> +lead: Victor Gevers
changed right?

2023-07-06 14:21 UTC, Lennaert89 commented on DIVD-2021-00020.md
> +patch_status: Pending
are they still pending? Looks like they have been assigned by now?

2023-07-06 14:21 UTC, Lennaert89 commented on DIVD-2021-00020.md
> +DIVD researcher Wietse Boonstra discovered five vulnerabilities in OSNEXUS QuantaStor. These vulnerabilities included a Server-Side Request Forgery, Remote Command Execution, Privilege Escalation and
je list ze alle 5, dus included vervangen door "are"

"Use of these" -> Abuse of these

2023-07-06 14:21 UTC, Lennaert89 commented on _cases/2021/DIVD-2021-00020.md
> +Based on our [CNA guidelines](/cna) we have given OSNexus aple time to acknowledge our findings (388 days) and ample time to fix the vulnerabilities (at least 6 months). And it is now time for a limi
aple -> ample

2023-07-06 14:21 UTC, Lennaert89 commented on _cases/2021/DIVD-2021-00020.md
> +excerpt: "There are multiple discovered vulnerabilities inside OSNEXUS QuantaStor involving injection (SSRF, XSS, RCE) and privilege escalation."
Replace start by "There have been various vulnerabilities discovered inside ..."

2023-07-06 14:21 UTC, Lennaert89 commented on DIVD-2021-00020.md
> +  event: First version of this case file.
als dit de blog post is dan "this case file" niet heel logisch

2023-07-06 14:21 UTC, Lennaert89 commented on _cves/CVE-2021-4406.md
> +      "title": "Authenticated Remote COmmand Execution as root in OSNEXUS QuantaStor version 6.0.0.355 and others",
COmmand -> Command

2023-07-06 14:21 UTC, Lennaert89 commented on _cves/CVE-2021-42083.md
> +              "value": "An authenticated attacker is able to create alerts that trigger a stored XSS attack.&nbsp;"
hoort die `&nbsp;` daar?

2023-07-06 14:21 UTC, Lennaert89 commented on _posts/2023/23-07-07-Limited-disclosure-OSNexus-vulnerabilities.md
> +The story of DIVD case [DIVD-2021-00020](/DIVD-2021-00020) is a story that started more then 1.5 years ago, when DIVD reserach [Wietse Boondsta](https://www.divd.nl/people/Wietse%20Boonstra/) discove
reserach -> researcher

2023-07-06 14:21 UTC, Lennaert89 commented on _posts/2023/23-07-07-Limited-disclosure-OSNexus-vulnerabilities.md
> +When OSNexus releast version 6.0.0.533 of their product on 22 Nov 2022 of which they stated that these vulnerabilities would be fix, we had good hopes to close this case, but it turned out that only
releast -> released
would be fix -> would be fixed

It also makes no sense, on line 10 we state the additional vuln CVE-2021-4406 is found in aug 2021, but lke 14 (this line) reads like it was found around 22nd Nov 2022 while verifying the fix in this new version.

2023-07-06 14:21 UTC, Lennaert89 commented on _posts/2023/23-07-07-Limited-disclosure-OSNexus-vulnerabilities.md
> +We again tried to address these vulnerabilities with OSNexus and again we were unable to get a reply from, or any kind of dialog with the vendor.
add comma between with and the vendor.

2023-07-06 14:21 UTC, Lennaert89 commented on _posts/2023/23-07-07-Limited-disclosure-OSNexus-vulnerabilities.md
> +If you are using any version of OSNexus QuantaStor we strongly recommend that you make sure it can only be access from trusted networks, as it may or may not contain Server Side Request Forgery (SSRF
it can only be access -> it can only be accessed
COmmand -> Command
Local Privilege Execution vulnerabilities? Think we mean Privilege Escalation here
 
 Would personally phrase "fully own" as "fully compromise"

2023-07-06 14:21 UTC, Lennaert89 commented on _posts/2023/23-07-07-Limited-disclosure-OSNexus-vulnerabilities.md
> +We strongly hope that OSNexus will reach out to us (via csirt@divd.nl) so we can work together to fix these vulnerabilities, but until that time we see disclosing these vulnerabilities and this produ
warnding -> warning
adminisrators  -> administrators
needed -> required

2023-07-07 11:50 UTC, MrSeccubus commented on DIVD-2021-00020.md
> +patch_status: Pending
Yup 6.0.0.355

2023-07-07 11:58 UTC, MrSeccubus commented on DIVD-2021-00020.md
> +patch_status: Pending
Unknown

2023-07-07 11:59 UTC, MrSeccubus commented on _cases/2021/DIVD-2021-00020.md
> +Based on our [CNA guidelines](/cna) we have given OSNexus aple time to acknowledge our findings (388 days) and ample time to fix the vulnerabilities (at least 6 months). And it is now time for a limi
✔️

2023-07-07 12:00 UTC, MrSeccubus commented on _posts/2023/23-07-07-Limited-disclosure-OSNexus-vulnerabilities.md
> +The story of DIVD case [DIVD-2021-00020](/DIVD-2021-00020) is a story that started more then 1.5 years ago, when DIVD reserach [Wietse Boondsta](https://www.divd.nl/people/Wietse%20Boonstra/) discove
✔️

2023-07-07 12:05 UTC, MrSeccubus commented on _posts/2023/23-07-07-Limited-disclosure-OSNexus-vulnerabilities.md
> +When OSNexus releast version 6.0.0.533 of their product on 22 Nov 2022 of which they stated that these vulnerabilities would be fix, we had good hopes to close this case, but it turned out that only
Fixed it. Well spotted.

2023-07-07 13:58 UTC, Lennaert89 requested changes

2023-07-07 13:58 UTC, Lennaert89 commented on _cases/2021/DIVD-2021-00020.md
> +excerpt: "Several serious vulnerabilities were discovered in OSNEXUS QuantaStor. We had difficulties working with the vendor and are now disclosing vulnerabilities and issueing a product warning."
issueing -> issuing

2023-07-07 13:58 UTC, Lennaert89 commented on _cases/2021/DIVD-2021-00020.md
> +  event: Five CVEs have been requested as assigned.
moet dit niet zijn "assigned as requested"?

2023-07-09 22:03 UTC, MrSeccubus commented
@Can you merge @Lennaert89 ?

2023-07-09 22:12 UTC, Lennaert89 approved these changes

2023-07-09 22:13 UTC, merged