DIVD-2023-00027.md
DIVD-NL/web-csirt pull request #651
Opened 2023-07-09 23:51 UTC by bizibdotnl

https://github.com/DIVD-NL/web-csirt/commit/42509fe09565740cb9c01adadc1b34ae928f6ad7

2023-07-10 05:33 UTC, MrSeccubus requested changes

2023-07-10 05:33 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00027.md
> +On the may 23th Ignite Realtime released a patch for CVE-2023-32315, which is an authentication bypass throught a path traversal vulnerability in Ingnite realtime Openfire software. DIVD will scan an
```suggestion
On the may 23th Ignite Realtime released a patch for {% cve CVE-2023-32315 %}, which is an authentication bypass through a path traversal vulnerability in Ingnite realtime Openfire software. DIVD will scan and notify systems that haven’t installed the patch and are vulnerable for this CVE.
```

2023-07-10 05:33 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00027.md
> +  (https://github.com/igniterealtime/Openfire/security/advisories/GHSA-gw42-f939-fhvm)
```suggestion
  [Openfire security advisory GHSA-gw42-f939](https://github.com/igniterealtime/Openfire/security/advisories/GHSA-gw42-f939-fhvm)
```

2023-07-10 05:33 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00027.md
> +
```suggestion
```

2023-07-10 05:33 UTC, MrSeccubus commented
Ziet er goed uit. Even een paar kleine tweaks.

2023-07-10 18:26 UTC, bizibdotnl commented
Thnx Frank for reviewing

2023-07-12 18:37 UTC, MrSeccubus approved these changes

2023-07-12 18:37 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00027.md
> +workaround: See vendor writeup:(https://github.com/igniterealtime/Openfire/security/advisories/GHSA-gw42-f939-fhvmA)
Dit ziet er nu zo uit:
![Screenshot 2023-07-12 at 20 29 45](https://github.com/DIVD-NL/web-csirt/assets/1063278/c18bcaef-452e-4232-95a5-6613185ed2d8)

Ik zou de haakjes weghalen

```suggestion
workaround: See vendor writeup: https://github.com/igniterealtime/Openfire/security/advisories/GHSA-gw42-f939-fhvmA
```

2023-07-12 18:37 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00027.md
> +  end: 2023-07-09
Doordat de duration nu 0 days is zie je niets in de gantt chart. Dat ziet er wat gek uit.
![Screenshot 2023-07-12 at 20 34 52](https://github.com/DIVD-NL/web-csirt/assets/1063278/dac25a39-f3f4-4d15-8bb1-52b05457da51)

De einddatum weghalen is de betere optie hier.

```suggestion
  end: 
```

2023-07-12 18:37 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00027.md
> +  end: 2023-07-09
Doordat de duration nu 0 days is zie je niets in de gantt chart. Dat ziet er wat gek uit.
![Screenshot 2023-07-12 at 20 34 52](https://github.com/DIVD-NL/web-csirt/assets/1063278/dac25a39-f3f4-4d15-8bb1-52b05457da51)

De einddatum weghalen is de betere optie hier.

```suggestion
  end: 
```

2023-07-12 18:37 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00027.md
> +  end: 2023-07-09
Doordat de duration nu 0 days is zie je niets in de gantt chart. Dat ziet er wat gek uit.
![Screenshot 2023-07-12 at 20 34 52](https://github.com/DIVD-NL/web-csirt/assets/1063278/dac25a39-f3f4-4d15-8bb1-52b05457da51)

De einddatum weghalen is de betere optie hier.

```suggestion
  end: 
```

2023-07-12 18:37 UTC, MrSeccubus requested changes
Nog een klein stukje.

2023-07-12 19:21 UTC, MrSeccubus requested changes

2023-07-12 19:21 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00027.md
> +workaround: "[See vendor writeup](https://github.com/igniterealtime/Openfire/security/advisories/GHSA-gw42-f939-fhvmA)"
Dit veld ondersteunt geen MarkDown

2023-07-12 19:41 UTC, bizibdotnl commented on _cases/2023/DIVD-2023-00027.md
> +workaround: See vendor writeup:(https://github.com/igniterealtime/Openfire/security/advisories/GHSA-gw42-f939-fhvmA)
okay

2023-07-12 19:42 UTC, bizibdotnl commented on _cases/2023/DIVD-2023-00027.md
> +workaround: "[See vendor writeup](https://github.com/igniterealtime/Openfire/security/advisories/GHSA-gw42-f939-fhvmA)"
resolved

2023-07-12 20:25 UTC, MrSeccubus approved these changes

2023-07-12 20:26 UTC, merged