casefile for DIVD-2023-00035
DIVD-NL/web-csirt pull request #670
Opened 2023-09-11 19:42 UTC by Maximand

2023-09-20 08:51 UTC, MrSeccubus requested changes

2023-09-20 08:51 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00035.md
> +To prevent remote code execution (RCE), only one PR needs to be fixed per platform.
What is a PR? Pull request?

2023-09-20 18:06 UTC, vcartman commented on _cases/2023/DIVD-2023-00035.md
> +Multiple vulnerabilities have been discovered in Juniper Networks SRX- and EX-Series. By chaining these vulnerabilities, an unauthenticated attacker can achieve Remote Command Execution and compromis
Aangepast.

2023-09-20 18:06 UTC, vcartman commented on _cases/2023/DIVD-2023-00035.md
> +excerpt: "A PHP External Variable Modification vulnerability in J-Web of Juniper Networks Junos OS on SRX and EX Series allows an unauthenticated, network-based attacker to control certain, important
Aangepast, het was RCE.

2023-09-20 18:06 UTC, vcartman commented on _cases/2023/DIVD-2023-00035.md
> +To prevent remote code execution (RCE), only one PR needs to be fixed per platform.
Aangepast

2023-09-20 18:44 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00035.md
> +excerpt: "A PHP External Variable Modification vulnerability in J-Web of Juniper Networks Junos OS on SRX and EX Series allows an unauthenticated, network-based attacker to control certain, important
👍

2023-09-20 20:00 UTC, MrSeccubus requested changes
Paar kleine dingetjes.

2023-09-23 08:23 UTC, MrSeccubus approved these changes
Lgtm

2023-09-23 08:23 UTC, merged