Divd 2023 00040
DIVD-NL/web-csirt pull request #685
Opened 2023-11-02 09:09 UTC by 82BBB00

First draft

2023-11-02 13:24 UTC, MrSeccubus requested changes

2023-11-02 13:24 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00040.md
> +patch_status: Full patched
```suggestion
patch_status: Patch available
```

2023-11-02 13:24 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00040.md
> +-workaround:  "Restrict access to the Traffic Management User Interface (TMUI) from the internet."
```suggestion
workaround:  "Restrict access to the Traffic Management User Interface (TMUI) from the internet."
```
Als je het minnetje niet weghaalt, dan wordt hij niet weergegeven.

2023-11-02 13:24 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00040.md
> +On October 26, 2023, F5 released security hotfixes for a critical unauthenticated RCE vulnerability in BIG-IP's Traffic Management User Interface (TMUI). This vulnerability is also tracked as CVE-202
```suggestion
On October 26, 2023, F5 released security hotfixes for a critical unauthenticated RCE vulnerability in BIG-IP's Traffic Management User Interface (TMUI). This vulnerability is also tracked as {% cve CVE-2023-46747 %}, with a CVSS v3.1 score of 9.8. This vulnerability is exploitable if the TMUI (managmenet web interface) is exposed to the internet. A threat actor with network access to the vulnerable system could bypass the configuration utility authentication and execute arbitrary system commands. On October 30, 2023, F5 updated the security advisory in order to warn about active exploitation in the wild.
```
Ik mis 30-10-2023 in je tijdlijn.

2023-11-02 13:24 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00040.md
> +## Summary
```suggestion
## Summary

```

2023-11-02 13:24 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00040.md
> +## What you can do
```suggestion

## What you can do

```

2023-11-02 13:24 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00040.md
> +For starters, it is recommended to restrict access to the Configuration Utility to only trusted networks or devices. F5 introduced Hotfixes in order to fix this issue. F5 provided as well a script th
```suggestion
For starters, it is recommended to restrict access to the Configuration Utility to only trusted networks or devices. This is in best practise that protects against vulnerabilities in this interface, which has historically proven to be a waeks spot.

F5 has released hotfixes that address this vulnerability. F5 also provides a script that works as workaround to mitigate this vulnerability. This script should only be used if you are not able to apply the relevant security hotfix or you are not able to upgrade to a version that has a security hotfix. However, this script CANNOT be used on any BIG-IP versions prior to 14.1.0.

```

2023-11-02 13:24 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00040.md
> +## What we are doing
```suggestion

## What we are doing

```

2023-11-22 19:37 UTC, vcartman submitted a review, later dismissed

2023-11-22 19:38 UTC, vcartman approved these changes

2023-11-22 19:42 UTC, merged