Update DIVD-2023-00042.md
DIVD-NL/web-csirt pull request #689
Opened 2023-11-28 19:20 UTC by Maximand

Kon t niet laten sorry

2023-11-28 19:38 UTC, WesselDIVD requested changes

2023-11-28 19:38 UTC, WesselDIVD commented on _cases/2023/DIVD-2023-00042.md
>    event: "DIVD created a list of vulnerable Confluence instancess"
instancess > instances

2023-11-28 19:38 UTC, WesselDIVD commented on _cases/2023/DIVD-2023-00042.md
>  * [Blog from Grafana](https://grafana.com/blog/2021/12/08/an-update-on-0day-cve-2021-43798-grafana-directory-traversal/)
kan weg

2023-11-28 19:38 UTC, WesselDIVD commented on _cases/2023/DIVD-2023-00042.md
>  * [Blog from Grafana](https://grafana.com/blog/2021/12/08/an-update-on-0day-cve-2021-43798-grafana-directory-traversal/)
Kan weg

2023-11-28 19:38 UTC, WesselDIVD commented on _cases/2023/DIVD-2023-00042.md
> +- start: 2023-11-22
2023-11-11 is de channel creation

2023-11-28 19:38 UTC, WesselDIVD commented on _cases/2023/DIVD-2023-00042.md
>  * [CVE-2021-43798](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-43798)
Kan ook weg

2023-11-28 19:38 UTC, WesselDIVD commented on _cases/2023/DIVD-2023-00042.md
>  author: Wessel Baltus
line 18 "all" > "All"

2023-12-17 12:26 UTC, MrSeccubus requested changes

2023-12-17 12:26 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00042.md
>    event: "DIVD created a list of vulnerable Confluence instancess"
```suggestion
  event: "DIVD created a list of vulnerable Confluence instances"
```

2023-12-20 17:38 UTC, Maximand commented
Ik weet niet zeker hoe (en of) ik hier nog aanpassingen aan moet maken. Er staat dat @MrSeccubus nog aanpassingen heeft voorgesteld maar ik kan ze nergens committen/toepassen omdat ze al staan gemarkeerd als toegepast.

2023-12-20 20:10 UTC, MrSeccubus commented
Regel 34 `instancess` -> `instances`

2023-12-20 20:42 UTC, WesselDIVD commented
Ik denk dat je de PR gewoon kan sluiten, deze zijn in andere al meegenomen en gefixt volgensmij

2023-12-31 14:49 UTC, closed without merging