DIVD-2023-00045 case file add
DIVD-NL/web-csirt pull request #695
Opened 2023-12-15 12:41 UTC by WesselDIVD

2023-12-15 12:41 UTC, WesselDIVD commented
Merged minor spelling issues for DIVD-2023-00042 into this PR

2023-12-17 12:24 UTC, MrSeccubus requested changes

2023-12-17 12:24 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00042.md
>  * List all resources here
```suggestion
```

2023-12-17 12:24 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00042.md
>  * List all resources here
Dit is nog van de template. Graag weghalen

2023-12-17 12:24 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00042.md
> +* https://confluence.atlassian.com/security/cve-2023-22518-improper-authorization-vulnerability-in-confluence-data-center-and-server-1311473907.html
```suggestion
* [Atlassian advisory](https://confluence.atlassian.com/security/cve-2023-22518-improper-authorization-vulnerability-in-confluence-data-center-and-server-1311473907.html)
```
Deze hyperlink is anders niet klikbaar.

2023-12-17 12:24 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00045.md
> +* List all resources here
```suggestion
```
Tempalte regel weghalen ajb.

2023-12-17 12:24 UTC, MrSeccubus commented on _cases/2023/DIVD-2023-00045.md
> +* [CVE-2023-22522](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-22522)
```suggestion
* {% cve CVE-2023-22522 %}
```
Daar hebben we een plugin voor.

2023-12-17 19:55 UTC, WesselDIVD commented
Bedankt voor de feedback Frank, zal er volgende keer op letten :)

2023-12-19 10:03 UTC, MrSeccubus approved these changes
Thanks

2023-12-19 10:03 UTC, merged