Create DIVD-2024-00003.md
DIVD-NL/web-csirt pull request #707
Opened 2024-01-19 13:12 UTC by sT0wn-nl

Eerste versie van de casefile

2024-01-22 10:23 UTC, Lennaert89 requested changes

2024-01-22 10:23 UTC, Lennaert89 commented on _cases/2024/DIVD-2024-00003.md
> +recommendation: "While the patch is under development, apply Ivanti’s mitigation, or take the appliance offline."
recommendation from other case?

2024-01-22 10:23 UTC, Lennaert89 commented on _cases/2024/DIVD-2024-00003.md
> +workaround:" "Restrict access to the webinterface of CrushFTP."
should have a space after the :

2024-01-22 10:23 UTC, Lennaert89 commented on _cases/2024/DIVD-2024-00003.md
> +- start: 2024-01-10
01-10 onder 01-15?

2024-01-22 10:23 UTC, Lennaert89 commented on _cases/2024/DIVD-2024-00003.md
> +Given that there is active exploitation, it is crucial the provided mitigation is applied as soon as possible or that the appliance is take offline until mitigations are available. It is also recomme
Eerste zin nog uit de ivanti case?

2024-01-22 10:45 UTC, MrSeccubus commented
Er is een build error in de action
```
Error: YAML Exception reading /home/runner/work/web-csirt/web-csirt/_cases/2024/DIVD-2024-00003.md: (<unknown>): did not find expected key while parsing a block mapping at line 2 column 1
```
Ik weer (nog) niet waarom hij hierop niet de build afbreekt, ga ik onderzoeken,.

2024-01-22 10:51 UTC, MrSeccubus requested changes

2024-01-22 10:51 UTC, MrSeccubus commented on _cases/2024/DIVD-2024-00003.md
> +workaround:" "Restrict access to the webinterface of CrushFTP."
```suggestion
workaround: "Restrict access to the webinterface of CrushFTP."
```
This was malformed yml.

2024-01-22 10:51 UTC, MrSeccubus commented on _cases/2024/DIVD-2024-00003.md
> +- All supported versions
Gbruike of de syntax:
```
versions:
- one
- two
```
of 
```
versions: one
```
Maar meng ze niet.

2024-01-24 14:10 UTC, Lennaert89 submitted a review, later dismissed

2024-01-31 15:51 UTC, MrSeccubus requested changes

2024-01-31 15:51 UTC, MrSeccubus commented on _cases/2024/DIVD-2024-00003.md
> +Given that there is active exploitation, it is crucial the provided mitigation is applied as soon as possible. It is also recommended to check the appliance for signs of previous exploitation. Upgrad
Dit is volgens mij nog steds een Ivanti/CrushFTP hybride.

2024-01-31 15:51 UTC, MrSeccubus commented on _cases/2024/DIVD-2024-00003.md
> +CVE-2023-43177 is a critical vulnerability in CrushFTP. The vulnerability could potentially allow unauthenticated attackers with network access to the CrushFTP Instance to write files in the local fi
```suggestion
{% cve CVE-2023-43177 %} is a critical vulnerability in CrushFTP. The vulnerability could potentially allow unauthenticated attackers with network access to the CrushFTP Instance to write files in the local file system and eventually in some versions could allow the executing of arbitrary system commands. 
```

2024-01-31 15:51 UTC, MrSeccubus commented on _cases/2024/DIVD-2024-00003.md
> +CVE-2023-43177 is a critical vulnerability in CrushFTP. The vulnerability could potentially allow unauthenticated attackers with network access to the CrushFTP Instance to write files in the local fi
Als ik dan toch bezig ben.

2024-01-31 15:51 UTC, MrSeccubus commented on _cases/2024/DIVD-2024-00003.md
> +Given that there is active exploitation, it is crucial the provided mitigation is applied as soon as possible. It is also recommended to check the appliance for signs of previous exploitation. Upgrad
Staat nog.

2024-01-31 15:53 UTC, MrSeccubus commented on _cases/2024/DIVD-2024-00003.md
> +Given that there is active exploitation, it is crucial the provided mitigation is applied as soon as possible or that the appliance is take offline until mitigations are available. It is also recomme
Nog steeds.

2024-02-19 19:36 UTC, MrSeccubus commented
@sT0wn-nl check `What you can do` nog even.
Dan kan deze *eindelijk* live.

2024-03-13 12:35 UTC, MrSeccubus approved these changes
Looks good to me

2024-03-13 12:37 UTC, MrSeccubus commented
Yes, we can finally merge this one.

2024-03-13 12:37 UTC, merged