Divd-2024-00031 case
DIVD-NL/web-csirt pull request #823
Opened 2024-08-08 08:50 UTC by vcartman

Divd-2024-00031 case release

2024-08-08 09:57 UTC, MrSeccubus commented
Ik mis de release van de CVE in dit PR, klopt dat?
Gaan we zo niet naar public but reserved?

2024-08-14 06:52 UTC, vcartman commented
> Ik mis de release van de CVE in dit PR, klopt dat? Gaan we zo niet naar public but reserved?

Verwerkt.

2024-08-14 07:27 UTC, MrSeccubus requested changes
Er stonden nog review comments open.

2024-08-14 07:27 UTC, MrSeccubus commented on _data/cves/2024/CVE-2024-27120.json
> +            }
Volgens mij moet die CWE-98 zijn.
https://cwe.mitre.org/data/definitions/98.html

2024-08-14 07:27 UTC, MrSeccubus commented on _data/cves/2024/CVE-2024-27120.json
> +            }
```suggestion
            {
              "status": "affected",
              "version": "*",
              "lessThan": "24.1.2"
            }
```

2024-09-12 18:40 UTC, vcartman commented on _data/cves/2024/CVE-2024-27120.json
> +            }
Het was gewijzigd van CWE-98 naar deze omdat het PHP LFI was in overleg met Alwin

2024-09-13 07:21 UTC, MrSeccubus commented on _data/cves/2024/CVE-2024-27120.json
> +            }
CWE-200 is wanneer gevoelige data "gewoon" wordt weergegeven, maar dit is een LFI, maar geen code execution.

Ik zou hem dan onder CWE-22 (path traversal) zetten. CWE-98 is idd LFI van PHP code, wat hier niet het geval is.

2024-09-13 07:23 UTC, MrSeccubus commented on _data/cves/2024/CVE-2024-27120.json
> +            }
CWE-41 is misschien een nog beter match https://cwe.mitre.org/data/definitions/41.html

2024-12-15 16:21 UTC, merged