Update credentials.md
DIVD-NL/web-csirt pull request #841
Opened 2024-09-11 15:22 UTC by ser1aa

Grammar optimizations

2024-09-12 05:51 UTC, MrSeccubus requested changes
Bedankt @ser1aa 
kun je nog even naar mijn commentaar kijken?

2024-09-12 05:51 UTC, MrSeccubus commented on credentials.md
> +The existence of leaked credentials is an ever-growing issue. Usernames and passwords are being stolen through malware, phishing or hacking. Afterwards, the leaked credentials are sold, traded and ex
Ik vind ‘issue’ te zwak. Dit is echt eeb ‘problem’.

2024-09-12 05:51 UTC, MrSeccubus commented on credentials.md
> +The scale of this problem is evident in the rising numbers linked to cases involving stolen credentials:
Scale is iets anders dan growth.

2024-09-12 05:51 UTC, MrSeccubus commented on credentials.md
> +We can't send large volumes of emails. Emailing millions or billions of addresses (of which a large portion is no longer active) will clog our email system and get us quickly on the "known spammers"
Can’t is te zwak vind ik.

2024-09-12 05:51 UTC, MrSeccubus commented on credentials.md
> +Thankfully, there are companies that handle the distribution of large volumes of emails. Managing such a high volume of email requires a specialized skill set. We've had discussions with these provid
Niet `Thankfully` want ook deze diensten zijn geen oplossing. Te duur en ze willen on niet. En dit zijn de bedrijven die reclame mailen.

2024-09-12 05:51 UTC, MrSeccubus commented on credentials.md
> +* What are the credentials used for?
Deze zin betekent nu was anders. Een credenrial voor gmail jan gebruikt worden om in te breken in iets anders, maar wij kunnen dat niet weten.

2024-09-12 05:51 UTC, MrSeccubus commented on credentials.md
> +* How and when was the leaked data obtained?
```suggestion
* How and when where the leaked credentials obtained?
```

2024-09-12 20:51 UTC, Lennaert89 commented on credentials.md
> +The existence of leaked credentials is an ever-growing issue. Usernames and passwords are being stolen through malware, phishing or hacking. Afterwards, the leaked credentials are sold, traded and ex
" DIVD has taken it upon ourselves" 3e persoon / 1e persoon

2024-09-13 11:21 UTC, ser1aa reviewed
better?

2024-09-13 13:35 UTC, MrSeccubus requested changes
Zoals besproken.

2024-09-13 13:35 UTC, MrSeccubus commented on credentials.md
> +Managing a high volume of emails requires a specialized skill set, there are companies that handle this kind of distribution. We've had discussions with these providers, and sending such large volume
```suggestion
Managing a high volume of emails requires a specialized skill set, there are companies that handle this kind of distribution. We've had discussions with these providers, and sending such large volumes of email can be quite expensive, in the range of five figures. As a non-profit organization run by volunteers, we simply don't have the budget for this kind of expenditure, and even if we did, we wouldn't be willing to allocate those funds in this manner. (If you are willing to [donate](https://www.divd.nl/donate) that kind of money, we can think of better ways to utilize it). Additionally, since we, by nature, do not have up front contant consent from the recipients of these emails, these service providers are hesitant to work with us.
```

2024-09-13 13:35 UTC, MrSeccubus commented on credentials.md
> +"When does being notified of a breach help, and when does it hurt? Without context, it's unlikely that a user can take any positive action. Does it help to know that you are now in 15 breaches instea
Vanwaar de quotes?

2024-09-13 13:35 UTC, MrSeccubus commented on credentials.md
> +* What are the credentials used for?
Hij is hetzelfde gebleven dus nog niet resolved wat mij betreft.

2024-09-13 13:35 UTC, MrSeccubus commented on credentials.md
> +* What are the credentials used for?
```suggestion
* What service/url are the credentials initially for?
```

2024-09-13 13:35 UTC, MrSeccubus commented on credentials.md
> +* How and when where the leaked credentials obtained?
```suggestion
* How, when, and where the leaked credentials obtained?
```

2024-09-13 14:35 UTC, ser1aa commented on credentials.md
> +"When does being notified of a breach help, and when does it hurt? Without context, it's unlikely that a user can take any positive action. Does it help to know that you are now in 15 breaches instea
Die mogen weg :$

2024-09-13 14:40 UTC, ser1aa reviewed
Please check if correct this time

2024-09-16 08:55 UTC, MrSeccubus requested changes
Ik heb nog 3 kleinigheidjes gevonden.

Dank je wel, is er een stuk leesbaarder op geworden.

2024-09-16 08:55 UTC, MrSeccubus commented on credentials.md
> +It is impossible for us to sent these large volumes of emails. Emailing millions or billions of addresses (of which a large portion is no longer active) will clog our email system and get us quickly
```suggestion
It is impossible for us to send these large volumes of emails. Emailing millions or billions of addresses (of which a large portion is no longer active) will clog our email system and get us quickly on the "known spammers" list of large email providers, effectively hurting the rest of our operation.
```

Sent met een t is verleden tijd. Dit is tegenwoordige tijd.

2024-09-16 08:55 UTC, MrSeccubus commented on credentials.md
> +Managing a high volume of emails requires a specialized skill set, there are companies that handle this kind of distribution. We've had discussions with these providers, and sending such large volume
```suggestion
Managing a high volume of emails requires a specialized skill set, there are companies that handle this kind of distribution. We've had discussions with these providers, and sending such large volumes of email can be quite expensive, in the range of five figures. As a non-profit organization run by volunteers, we simply don't have the budget for this kind of expenditure, and even if we did, we wouldn't be willing to allocate those funds in this manner. (If you are willing to [donate](https://www.divd.nl/donate) that kind of money, we can think of better ways to utilize it). Additionally, since we, by nature, do not have up front consent from the recipients of these emails, these service providers are hesitant to work with us.
```
Stray (odd) word.

2024-09-16 08:55 UTC, MrSeccubus commented on credentials.md
> +* How, when, and where the leaked credentials obtained?
```suggestion
* How, when, and where have the leaked credentials been obtained?
```
Zo, tongbreker (en vingerbreker)....

2024-09-16 14:52 UTC, ser1aa reviewed
better? :)

2024-09-16 15:08 UTC, MrSeccubus approved these changes
❤️ thanks!

2024-09-16 15:09 UTC, merged