Update DIVD-2024-00032.md
DIVD-NL/web-csirt pull request #842
Opened 2024-09-14 12:21 UTC by sT0wn-nl

2de mailronde, case gesloten.

2024-09-15 06:50 UTC, MrSeccubus approved these changes
Lgtm

2024-09-15 06:52 UTC, MrSeccubus commented
Kijk even naar de output van de build. 

```
ERROR CasesPlugin: Case DIVD-2024-00032, is 'Closed' but end date is not set
```

2024-09-15 06:54 UTC, MrSeccubus requested changes
Start date gewijzigd ipv end date gezet.

2024-09-15 06:54 UTC, MrSeccubus commented on _cases/2024/DIVD-2024-00032.md
> +start: 2024-09-14
Dit had denk ik de end date moeten zijn.

2024-09-16 08:24 UTC, sT0wn-nl reviewed
Fix in enddate

2024-09-16 08:38 UTC, MrSeccubus commented
Build still fails with:
```
ERROR CasesPlugin: Case DIVD-2024-00032, is 'Closed' but end date is not set
```

2024-09-16 08:39 UTC, MrSeccubus requested changes
End datum zetten ajb!

2024-09-16 08:39 UTC, MrSeccubus commented on _cases/2024/DIVD-2024-00032.md
> +start: 2024-09-14
```suggestion
start: 2024-07-03
```

2024-09-16 08:39 UTC, MrSeccubus commented on _cases/2024/DIVD-2024-00032.md
>  end:
```suggestion
end: 2024-09-14
```

2024-09-16 08:39 UTC, MrSeccubus commented on _cases/2024/DIVD-2024-00032.md
> +start: 2024-09-14
Volgens mij is dit wat je wil.

2024-09-16 08:39 UTC, MrSeccubus commented on _cases/2024/DIVD-2024-00032.md
>  end:
En moet je dit doen om de build weer goed te laten gaan.

2024-09-17 11:44 UTC, MrSeccubus approved these changes
:+1:

2024-09-17 11:44 UTC, merged