Update DIVD-2024-00030.md
DIVD-NL/web-csirt pull request #845
Opened 2024-09-26 07:45 UTC by kscdivd

Added new timeline items and extra info

2024-09-26 08:47 UTC, MrSeccubus requested changes
Onder "More Information" staat CVE-2024-6342 dubbel, een keer als hyperlink en een keer zonder. Kan die zonder hyperlink weg?

2024-09-26 08:47 UTC, MrSeccubus commented on _cases/2024/DIVD-2024-00030.md
> +  event: "DIVD switched in new fingerprint to check the device firmware creation-date"
```suggestion
  event: "DIVD switched to new fingerprint that checks the device firmware creation-date"
```

2024-09-26 09:14 UTC, kscdivd commented on _cases/2024/DIVD-2024-00030.md
> +  event: "DIVD switched in new fingerprint to check the device firmware creation-date"
Both suggestion are fixed.

2024-09-27 05:13 UTC, MrSeccubus approved these changes
👍

2024-09-27 05:13 UTC, merged