adding casefile for DIVD case DIVD-2024-00039
DIVD-NL/web-csirt pull request #846
Opened 2024-10-01 12:40 UTC by WesselDIVD

Casefile addition including all information on DIVD case DIVD-2024-00039

2024-10-02 04:55 UTC, JstRelax requested changes
Paar wijzigingen, voor de rest prima!

2024-10-02 04:55 UTC, JstRelax commented on _cases/2024/DIVD-2024-00039.md
> +excerpt: "In Apache OFBiz, version 18.12.14and below, a Incorrect Authorization vulnerability exists that allows pre-authentication remote code execution (RCE) resulting in a attacker being able to e
```suggestion
excerpt: "In Apache OFBiz, version 18.12.14 and below, an Incorrect Authorization vulnerability exists that allows pre-authentication remote code execution (RCE) resulting in an attacker being able to execute arbitrary commands on the affected system by sending a specially crafted HTTP request."
```

2024-10-02 04:55 UTC, JstRelax commented on _cases/2024/DIVD-2024-00039.md
> +The Apache OFBiz versions 18.12.14 and below are vulnerable. Upgrade to version 18.12.15 as soon as possible.
```suggestion
The Apache OFBiz versions 18.12.14 and below are vulnerable. Upgrade to version 18.12.15 or higher as soon as possible.
```

2024-10-02 04:55 UTC, JstRelax commented on _cases/2024/DIVD-2024-00039.md
> +title: "Incorrect Authorization vulnerability in Apache OFBiz resulting in RCE"
```suggestion
title: "Incorrect Authorization vulnerability in Apache OFBiz resulting in Remote Code Execution"
```

2024-10-02 19:33 UTC, vcartman approved these changes

2024-10-02 19:34 UTC, vcartman approved these changes

2024-10-03 08:02 UTC, JstRelax approved these changes
LGTM

2024-10-03 08:02 UTC, merged