Create DIVD-2024-00042.md
DIVD-NL/web-csirt pull request #858
Opened 2024-10-18 09:41 UTC by sT0wn-nl

Eerst versie van casefile Solarwinds Helpdesk

2024-10-18 09:50 UTC, sT0wn-nl reviewed
fixes..

2024-10-18 09:53 UTC, sT0wn-nl reviewed
Nog kortere titel

2024-10-21 05:15 UTC, MrSeccubus approved these changes

2024-10-21 05:15 UTC, MrSeccubus commented on _cases/2024/DIVD-2024-00042.md
> +start: 2024–09-23
```suggestion
start: 2024–09-24
```
Inconsistent met eerste even.

2024-10-21 05:15 UTC, MrSeccubus commented on _cases/2024/DIVD-2024-00042.md
> +start: 2024–09-23
Event that is.

2024-10-21 05:15 UTC, MrSeccubus commented on _cases/2024/DIVD-2024-00042.md
> +Solarwinds Web Help Desk, has disclosed two critical security vulnerabilities affecting versions released prior to 12.8.3 HF2. The vulnerability, identified as CVE-2024-28987, involves a hardcoded cr
```suggestion
Solarwinds Web Help Desk, has disclosed two critical security vulnerabilities affecting versions released prior to 12.8.3 HF2. The vulnerability, identified as {% cve CVE-2024-28987 %}, involves a hardcoded credential vulnerability allowing remote unauthenticated user to access internal functionality and modify data. The other vulnerability, identified as {% cve CVE-2024-28987 %}, susceptible to a Java Deserialization Remote Code Execution vulnerability that, if exploited, would allow an attacker to run commands on the host machine.
```

2024-10-21 05:15 UTC, MrSeccubus commented on _cases/2024/DIVD-2024-00042.md
> +To remediate CVE-2024-28987 and CVE-2024-28987, update to version 12.8.3 HF3. You can find a link to the Solarwinds Web Helpdesk bulletin at the bottom of this post. Please note that applying the hot
```suggestion
To remediate {% cve CVE-2024-28987 %} and {% cve CVE-2024-28987 %}, update to version 12.8.3 HF3. You can find a link to the Solarwinds Web Helpdesk bulletin at the bottom of this post. Please note that applying the hotfix requires some manual steps which are explained in the security bulletin.
```

2024-10-21 05:15 UTC, MrSeccubus commented on _cases/2024/DIVD-2024-00042.md
> +* [National Vulnerability Database for CVE-2024-28987](https://nvd.nist.gov/vuln/detail/CVE-2024-28987)
Waarom ook de links naar NVD?

2024-10-21 05:15 UTC, MrSeccubus requested changes
Chens needed. Approval was per abuis.

2024-10-21 05:18 UTC, MrSeccubus commented
Er staat ook een build error:
`ERROR CasesPlugin: Case DIVD-2024-00042, has invalid start date '2024–09-23', it should be a valid date`
Is een verkeerd soort streepje in de date gekomen denk ik (copy pasta van Slack?)

2024-10-21 11:08 UTC, sT0wn-nl reviewed
Aanpassingen nav CVE-2024-28988

2024-10-24 09:48 UTC, JstRelax approved these changes
Wijzigingen zijn gedaan. Ziet er nu goed uit.

2024-10-24 09:49 UTC, JstRelax approved these changes
LGTM

2024-10-26 07:47 UTC, MrSeccubus approved these changes

2024-10-26 07:47 UTC, merged