Update credentials.md
DIVD-NL/web-csirt pull request #869
Opened 2024-11-12 10:06 UTC by ser1aa

Rephrased some sentences (trying to not change the message) and removed some spelling mistakes.

2024-11-20 18:56 UTC, MrSeccubus requested changes
Een paar kleine dingen. Kun je er nog even naar kijken?

2024-11-20 18:56 UTC, MrSeccubus commented on credentials.md
> +Lots of credentials are from so-called [combo lists](https://scirge.com/glossary/combo-list). These lists combine credentials from different breaches, are traded, and are often of low quality. Most o
```suggestion
Lots of credentials are from so-called [combo lists](https://scirge.com/glossary/combo-list). These lists combine credentials from different breaches, are traded, and are often of low quality. Most of the time, these lists only contain a username and password and are devoid of any context, like when the credentials were "harvested", which platform, service, or system they initially belonged to, and where the breach occurred.
```
Ik vind die comma raar staan binnen de quotes, ligt dat aan mij?

2024-11-20 18:56 UTC, MrSeccubus commented on credentials.md
> +This means we will not process combo lists without context.
Ik heb het idee dat deze nu minder sterk geworden is.
In het Nederlands: We processen combolijsten niet, tenzij er voldoende context by zit.

Jouw versie volt voor mij meer als: zonder context processen we dit niet.

2024-11-21 10:55 UTC, ser1aa commented on credentials.md
> +Lots of credentials are from so-called [combo lists](https://scirge.com/glossary/combo-list). These lists combine credentials from different breaches, are traded, and are often of low quality. Most o
De comma staat daar om de leesbaarheid van te verbeteren. Zonder de comma klopt de zin niet meer

2024-11-21 11:03 UTC, MrSeccubus commented on credentials.md
> +Lots of credentials are from so-called [combo lists](https://scirge.com/glossary/combo-list). These lists combine credentials from different breaches, are traded, and are often of low quality. Most o
Dat snap ik maar dan schrijf je toch `”harvested”,` ipv `”harvested,”`

2024-11-21 11:08 UTC, ser1aa commented on credentials.md
> +We feel that the content of the password itself is often vital context in the decision on what to do about leaked credentials. However, we believe that distributing plain text passwords is even more
Ik pas het aan

2024-11-21 11:10 UTC, ser1aa reviewed
Beter zo?

2024-11-22 08:46 UTC, JstRelax requested changes
De score is gebaseerd op 0 tot 1
Dus dit dient 0.4 te zijn.

2024-11-22 08:51 UTC, JstRelax commented on credentials.md
> +In order to address ethical concerns regarding the sharing of PII with government organisations of countries with a less than ideal situation with regard to the upholding of human rights, we will onl
Ook aangepast op - https://github.com/DIVD-NL/web-www-v2/pull/615

2024-12-15 16:03 UTC, MrSeccubus approved these changes
:+1:

2024-12-15 16:04 UTC, merged

2024-12-16 12:39 UTC, ser1aa commented on credentials.md
> +Lots of credentials are from so-called [combo lists](https://scirge.com/glossary/combo-list). These lists combine credentials from different breaches, are traded, and are often of low quality. Most o
Ja, je hebt gelijk

2024-12-16 12:45 UTC, ser1aa commented on credentials.md
> +Lots of credentials are from so-called [combo lists](https://scirge.com/glossary/combo-list). These lists combine credentials from different breaches, are traded, and are often of low quality. Most o
Het lukt mij niet om het pull request aan te passen, kan jij dat doen eventueel @MrSeccubus ?

2024-12-16 12:59 UTC, JstRelax commented on credentials.md
> +Lots of credentials are from so-called [combo lists](https://scirge.com/glossary/combo-list). These lists combine credentials from different breaches, are traded, and are often of low quality. Most o
https://github.com/DIVD-NL/web-csirt/pull/894
PR staat open om het op te lossen

Deze PR is al merged