Adding  DIVD-2024-00051
DIVD-NL/web-csirt pull request #890
Opened 2024-12-09 20:18 UTC by flor1der

Adding  DIVD-2024-00051

2024-12-10 19:19 UTC, oscar-vlugt requested changes
Looks great overall. Some remarks hat should be easy to tackle.

2024-12-10 19:19 UTC, oscar-vlugt commented on _cases/2024/DIVD-2024-00051.md
> +excerpt: "Improper authorization vulnerabilty, cve-2024-11680, in open-source file-sharing application: ProjectSend,"
Trailing komma after ProjectSend

2024-12-10 19:19 UTC, oscar-vlugt commented on _cases/2024/DIVD-2024-00051.md
> +recommendation: "Upgrade to R1720 or later"
I prefer either the capital R or the lowercase R throughout the entire case file to keep the style the same.

2024-12-10 19:19 UTC, oscar-vlugt commented on _cases/2024/DIVD-2024-00051.md
> +{% include timeline.html %}
We should add a section that is labeled "More Information" after the timeline that has some information on the CVEs, the potential exploit and maybe a blog/write-up for reference when that is available. Refer to other case files to find an example layout.

2024-12-11 20:48 UTC, flor1der commented on _cases/2024/DIVD-2024-00051.md
> +recommendation: "Upgrade to R1720 or later"
Adjusting everything to r1720 since that's the official naming convention used as per the ProjectSend website.

2024-12-11 20:53 UTC, flor1der commented
Thanks @oscar-vlugt, the requested changes have been made and the pull request is ready for re-review.

2024-12-11 20:59 UTC, oscar-vlugt approved these changes
LGTM

2024-12-11 20:59 UTC, merged